#CUDA_VISIBLE_DEVICES=0 python main.py --model ULA_VAE --dataset celeba --binarize False --batch_size 50 --num_samples 1 --max_epochs 100 --step_size 0.01 --K 5 --variance_sensitive_step True --ula_skip_threshold 0.3 --acceptance_rate_target 0.9 --annealing_scheme all_learnable --limit_train_batches 0.1 --limit_val_batches 0.1 --grad_clip_val 50 --gpus 1
#CUDA_VISIBLE_DEVICES=0 python main.py --model ULA_VAE --dataset celeba --binarize False --batch_size 50 --num_samples 1 --max_epochs 100 --step_size 0.01 --K 10 --variance_sensitive_step True --ula_skip_threshold 0.3 --acceptance_rate_target 0.9 --annealing_scheme all_learnable --limit_train_batches 0.1 --limit_val_batches 0.1 --grad_clip_val 50 --gpus 1
#
#CUDA_VISIBLE_DEVICES=0 python main.py --model AIS_VAE --dataset celeba --binarize False --batch_size 50 --num_samples 5 --max_epochs 100 --step_size 0.01 --K 3 --variance_sensitive_step True --use_barker False --acceptance_rate_target 0.8 --annealing_scheme all_learnable --limit_train_batches 0.1 --limit_val_batches 0.1 --gpus 1
#CUDA_VISIBLE_DEVICES=0 python main.py --model AIS_VAE --dataset celeba --binarize False --batch_size 50 --num_samples 5 --max_epochs 100 --step_size 0.01 --K 5 --variance_sensitive_step True --use_barker False --acceptance_rate_target 0.8 --annealing_scheme all_learnable --limit_train_batches 0.1 --limit_val_batches 0.1 --gpus 1

CUDA_VISIBLE_DEVICES=0 python main.py --model ULA_VAE --dataset mnist --binarize True --batch_size 50 --num_samples 1 --max_epochs 100 --step_size 0.01 --K 5 --variance_sensitive_step True --ula_skip_threshold 0.3 --acceptance_rate_target 0.9 --annealing_scheme all_learnable --gpus 1
CUDA_VISIBLE_DEVICES=0 python main.py --model ULA_VAE --dataset mnist --binarize True --batch_size 50 --num_samples 1 --max_epochs 100 --step_size 0.01 --K 10 --variance_sensitive_step True --ula_skip_threshold 0.3 --acceptance_rate_target 0.9 --annealing_scheme all_learnable --gpus 1

CUDA_VISIBLE_DEVICES=0 python main.py --model AIS_VAE --dataset mnist --binarize True --batch_size 50 --num_samples 5 --max_epochs 100 --step_size 0.01 --K 3 --variance_sensitive_step True --use_barker False --acceptance_rate_target 0.8 --annealing_scheme all_learnable --gpus 1
CUDA_VISIBLE_DEVICES=0 python main.py --model AIS_VAE --dataset mnist --binarize True --batch_size 50 --num_samples 5 --max_epochs 100 --step_size 0.01 --K 5 --variance_sensitive_step True --use_barker False --acceptance_rate_target 0.8 --annealing_scheme all_learnable --gpus 1