#CUDA_VISIBLE_DEVICES=1 python main.py --model ULA_VAE --dataset celeba --binarize False --batch_size 50 --num_samples 1 --max_epochs 100 --step_size 0.01 --K 1 --variance_sensitive_step True --ula_skip_threshold 0.1 --acceptance_rate_target 0.9 --limit_train_batches 0.1 --limit_val_batches 0.1 --gpus 1
#CUDA_VISIBLE_DEVICES=1 python main.py --model ULA_VAE --dataset celeba --binarize False --batch_size 50 --num_samples 1 --max_epochs 100 --step_size 0.01 --K 3 --variance_sensitive_step True --ula_skip_threshold 0.1 --acceptance_rate_target 0.9 --limit_train_batches 0.1 --limit_val_batches 0.1 --gpus 1
#CUDA_VISIBLE_DEVICES=1 python main.py --model ULA_VAE --dataset celeba --binarize False --batch_size 50 --num_samples 1 --max_epochs 100 --step_size 0.01 --K 5 --variance_sensitive_step True --ula_skip_threshold 0.1 --acceptance_rate_target 0.9 --limit_train_batches 0.1 --limit_val_batches 0.1 --gpus 1
#CUDA_VISIBLE_DEVICES=1 python main.py --model ULA_VAE --dataset celeba --binarize False --batch_size 50 --num_samples 1 --max_epochs 100 --step_size 0.01 --K 7 --variance_sensitive_step True --ula_skip_threshold 0.1 --acceptance_rate_target 0.9 --limit_train_batches 0.1 --limit_val_batches 0.1 --gpus 1
#CUDA_VISIBLE_DEVICES=1 python main.py --model ULA_VAE --dataset celeba --binarize False --batch_size 50 --num_samples 1 --max_epochs 100 --step_size 0.01 --K 10 --variance_sensitive_step True --ula_skip_threshold 0.1 --acceptance_rate_target 0.9 --limit_train_batches 0.1 --limit_val_batches 0.1 --gpus 1

#CUDA_VISIBLE_DEVICES=1 python main.py --model IWAE --dataset cifar --act_func gelu --binarize False --hidden_dim 64 --batch_size 50 --net_type conv --num_samples 10 --max_epochs 100 --gpus 1
#CUDA_VISIBLE_DEVICES=1 python main.py --model VAE --dataset celeba --act_func gelu --binarize False --hidden_dim 64 --batch_size 50 --net_type conv --num_samples 1 --max_epochs 100 --limit_train_batches 0.1 --limit_val_batches 0.1 --gpus 1
#CUDA_VISIBLE_DEVICES=1 python main.py --model IWAE --dataset celeba --act_func gelu --binarize False --hidden_dim 64 --batch_size 50 --net_type conv --num_samples 10 --max_epochs 100 --limit_train_batches 0.1 --limit_val_batches 0.1 --gpus 1

CUDA_VISIBLE_DEVICES=1 python main.py --model ULA_VAE --dataset celeba --binarize False --batch_size 50 --num_samples 1 --max_epochs 30 --step_size 0.01 --K 1 --variance_sensitive_step True --ula_skip_threshold 0.1 --acceptance_rate_target 0.5 --limit_train_batches 0.1 --limit_val_batches 0.1 --gpus 1
CUDA_VISIBLE_DEVICES=1 python main.py --model ULA_VAE --dataset celeba --binarize False --batch_size 50 --num_samples 1 --max_epochs 30 --step_size 0.01 --K 1 --variance_sensitive_step True --ula_skip_threshold 0.1 --acceptance_rate_target 0.75 --limit_train_batches 0.1 --limit_val_batches 0.1 --gpus 1
CUDA_VISIBLE_DEVICES=1 python main.py --model ULA_VAE --dataset celeba --binarize False --batch_size 50 --num_samples 1 --max_epochs 30 --step_size 0.01 --K 1 --variance_sensitive_step True --ula_skip_threshold 0.1 --acceptance_rate_target 0.9 --limit_train_batches 0.1 --limit_val_batches 0.1 --gpus 1
CUDA_VISIBLE_DEVICES=1 python main.py --model ULA_VAE --dataset celeba --binarize False --batch_size 50 --num_samples 1 --max_epochs 30 --step_size 0.01 --K 1 --variance_sensitive_step True --ula_skip_threshold 0.1 --acceptance_rate_target 0.99 --limit_train_batches 0.1 --limit_val_batches 0.1 --gpus 1

CUDA_VISIBLE_DEVICES=1 python main.py --model ULA_VAE --dataset celeba --binarize False --batch_size 50 --num_samples 1 --max_epochs 30 --step_size 0.01 --K 1 --variance_sensitive_step True --ula_skip_threshold 0.25 --acceptance_rate_target 0.5 --limit_train_batches 0.1 --limit_val_batches 0.1 --gpus 1
CUDA_VISIBLE_DEVICES=1 python main.py --model ULA_VAE --dataset celeba --binarize False --batch_size 50 --num_samples 1 --max_epochs 30 --step_size 0.01 --K 1 --variance_sensitive_step True --ula_skip_threshold 0.25 --acceptance_rate_target 0.75 --limit_train_batches 0.1 --limit_val_batches 0.1 --gpus 1
CUDA_VISIBLE_DEVICES=1 python main.py --model ULA_VAE --dataset celeba --binarize False --batch_size 50 --num_samples 1 --max_epochs 30 --step_size 0.01 --K 1 --variance_sensitive_step True --ula_skip_threshold 0.25 --acceptance_rate_target 0.9 --limit_train_batches 0.1 --limit_val_batches 0.1 --gpus 1
CUDA_VISIBLE_DEVICES=1 python main.py --model ULA_VAE --dataset celeba --binarize False --batch_size 50 --num_samples 1 --max_epochs 30 --step_size 0.01 --K 1 --variance_sensitive_step True --ula_skip_threshold 0.25 --acceptance_rate_target 0.99 --limit_train_batches 0.1 --limit_val_batches 0.1 --gpus 1

CUDA_VISIBLE_DEVICES=1 python main.py --model ULA_VAE --dataset celeba --binarize False --batch_size 50 --num_samples 1 --max_epochs 30 --step_size 0.01 --K 1 --variance_sensitive_step True --ula_skip_threshold 0.5 --acceptance_rate_target 0.5 --limit_train_batches 0.1 --limit_val_batches 0.1 --gpus 1
CUDA_VISIBLE_DEVICES=1 python main.py --model ULA_VAE --dataset celeba --binarize False --batch_size 50 --num_samples 1 --max_epochs 30 --step_size 0.01 --K 1 --variance_sensitive_step True --ula_skip_threshold 0.5 --acceptance_rate_target 0.75 --limit_train_batches 0.1 --limit_val_batches 0.1 --gpus 1
CUDA_VISIBLE_DEVICES=1 python main.py --model ULA_VAE --dataset celeba --binarize False --batch_size 50 --num_samples 1 --max_epochs 30 --step_size 0.01 --K 1 --variance_sensitive_step True --ula_skip_threshold 0.5 --acceptance_rate_target 0.9 --limit_train_batches 0.1 --limit_val_batches 0.1 --gpus 1
CUDA_VISIBLE_DEVICES=1 python main.py --model ULA_VAE --dataset celeba --binarize False --batch_size 50 --num_samples 1 --max_epochs 30 --step_size 0.01 --K 1 --variance_sensitive_step True --ula_skip_threshold 0.5 --acceptance_rate_target 0.99 --limit_train_batches 0.1 --limit_val_batches 0.1 --gpus 1