#CUDA_VISIBLE_DEVICES=1 python main.py --model ULA_VAE --dataset cifar --binarize False --hidden_dim 128 --batch_size 50 --num_samples 1 --max_epochs 100 --step_size 0.01 --K 5 --variance_sensitive_step True --ula_skip_threshold 0.3 --acceptance_rate_target 0.9 --annealing_scheme sigmoidal --gpus 1
#CUDA_VISIBLE_DEVICES=1 python main.py --model ULA_VAE --dataset cifar --binarize False --hidden_dim 128 --batch_size 50 --num_samples 1 --max_epochs 100 --step_size 0.01 --K 10 --variance_sensitive_step True --ula_skip_threshold 0.3 --acceptance_rate_target 0.9 --annealing_scheme sigmoidal --gpus 1
#
#CUDA_VISIBLE_DEVICES=1 python main.py --model AIS_VAE --dataset cifar --binarize False --hidden_dim 128 --batch_size 50 --num_samples 5 --max_epochs 100 --step_size 0.01 --K 3 --variance_sensitive_step True --use_barker False --acceptance_rate_target 0.8 --use_alpha_annealing True --annealing_scheme sigmoidal --gpus 1
#CUDA_VISIBLE_DEVICES=1 python main.py --model AIS_VAE --dataset cifar --binarize False --hidden_dim 128 --batch_size 50 --num_samples 5 --max_epochs 100 --step_size 0.01 --K 5 --variance_sensitive_step True --use_barker False --acceptance_rate_target 0.8 --use_alpha_annealing True --annealing_scheme sigmoidal --gpus 1

CUDA_VISIBLE_DEVICES=1 python main.py --model ULA_VAE --dataset mnist --binarize True --batch_size 50 --num_samples 1 --max_epochs 100 --step_size 0.01 --K 10 --variance_sensitive_step True --ula_skip_threshold 0.3 --acceptance_rate_target 0.9 --annealing_scheme sigmoidal --gpus 1

CUDA_VISIBLE_DEVICES=1 python main.py --model AIS_VAE --dataset mnist --binarize True --batch_size 50 --num_samples 5 --max_epochs 100 --step_size 0.01 --K 3 --variance_sensitive_step True --use_barker False --acceptance_rate_target 0.8 --annealing_scheme sigmoidal --gpus 1
CUDA_VISIBLE_DEVICES=1 python main.py --model AIS_VAE --dataset mnist --binarize True --batch_size 50 --num_samples 5 --max_epochs 100 --step_size 0.01 --K 10 --variance_sensitive_step True --use_barker False --acceptance_rate_target 0.8 --annealing_scheme sigmoidal --gpus 1